name: DevSecOps

on:
  push:
    branches:
      - 'magno'

permissions: write-all

jobs:

  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan
    needs: snyk
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://juice-shop.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
