name: DevSecOps

on:
  push:
    branches:
      - 'magno'

permissions: write-all

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: ZAP Scan
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://juice-shop.herokuapp.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
